---
title: "Stat545B-A1"
author: "Nicole"
date: "2023-10-29"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Stat 545B - Assignment 1

#Excercise 1
```{r}
#loading libraries 
library(tidyverse)
library(ggplot2)
library(datateachr)
library(testthat)

```

```{r}
install.packages("proto")
```


```{r}
#The function I choose to make incorpurts 
mean_median_mode_range <- function(vector){
    mean <- mean(vector)
    median <- median(vector)
    range <- range(vector)
    return(c(mean, median,range))
}


print(mean_median_mode_range(c(1, 1, 1, 2, 3)))

```

```{r}
calculate_BMI_women <- function(weight, height){
    (703 * weight/(height^2))
}

calculate_BMI_women(130, 5.9)
```


```{r}
#Exercise 1: Make a Function

#The function I choose to make is a plot which I used a lot in the Stat545 mda. This function creates a standard scatterplot. 

easyplot <- function(data, x, y, na.rm = TRUE){
  ggplot(data, aes({{x}}, {{y}})) + 
  geom_point(size = 0.8, alpha = 0.5, color = "blue") 
}


easyplot(vancouver_trees, diameter, height_range_id)



#Your function should be reasonably flexible on its inputs. Here is an example of a function that is not reasonably flexible: a function called count_missing_values_by_group() that only works when the data frame has columns that are all of type fct??

#Your function includes appropriate arguments. (Do you handle NA’s appropriately? Are you using the ellipsis properly? etc.)??

```

```{r}
#Exercise 2: Document your Function


#' @title easyplot()
#' @description This function creates a standard scatter plot with blue points using ggplot. This function makes it easy to create a plot to look at the relationship between two variables. 
#' @details 


#Creating a scatter plot 
#' @paraam data A dataset.
#I named this variable data as it describes that a data set should be inputted 
#data is green?
#' @param x A variable dataset.
#I named this variable x to describe one of the variables being investigated 
#' @param y A variable dataset.
#I named this variable y to describe one of the variables being investigated 
#' @returns A scatter plot using x versus y. 



#Function description: In 1-2 brief sentences, describe what the function does.
#Document each argument with the @param tag, making sure to justify why you named the parameter as you did.??
#(Justification for naming is not often needed, but we want to hear your reasoning.)
#What the function returns, using the @return tag.
```

```{r}
#Exercise 3: Include examples 

easyplot(vancouver_trees, diameter, height_range_id)
```

```{r}
easyplot(cancer_sample, radius_mean, area_mean)
```

```{r}
easyplot(flow_sample, year, flow)
```

```{r}
#Exercise 4: Test the Function

test_that("Function creates a ggplot",{
  ep <- easyplot(vancouver_trees)
  expect_is(ep,"ggplot")
})

#can I use an example dataset?

```


```{r}
test_that("Function uses the correct given dataset", {
  ep <- easyplot(vancouver_trees)
  expect_that(vancouver_trees, equals(ep$data))
})
```

```{r}
test_that("x-axid is labelled 'diameter'",{
  ep <- easyplot(vancouver_trees)
  expect_identical(ep$vancouver_trees$diameter, "diameter")
})
```


```{r}

library(proto)
test_that("Plot layers match expectations",{
ep <- easyplot(vancouver_trees)
  expect_is(ep$layers[[1]], "proto")
  expect_identical(ep$layers[[1]]$geom$objname, "point")
  expect_identical(ep$layers[[1]]$colour$objname, "blue")
})

```

